<?php

namespace Database\Seeders;

use App\Models\AllColor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AllColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $allcolor = [
            [ 'color_name' => 'IVORY'],
            [ 'color_name' => 'PRIMROSE'],
            [ 'color_name' => 'BUTTERCUP'],
            [ 'color_name' => 'SOFT LIME'],
            [ 'color_name' => 'TULIP YELLOW'],
            [ 'color_name' => 'LEMON'],
            [ 'color_name' => 'YELLOW'],
            [ 'color_name' => 'CANARY'],
            [ 'color_name' => 'SUNFLOWER'],
            [ 'color_name' => 'ALMOND'],
            [ 'color_name' => 'BLUSH'],
            [ 'color_name' => 'SAFFRON'],
            [ 'color_name' => 'VANILLA'],
            [ 'color_name' => 'PASTEL YELLOW'],
            [ 'color_name' => 'MUSTARD'],
            [ 'color_name' => 'OATMEAL'],
            [ 'color_name' => 'APRICOT'],
            [ 'color_name' => 'HONEYCOMB'],
            [ 'color_name' => 'GOLD'],
            [ 'color_name' => 'AMBER'],
            [ 'color_name' => 'PUMPKIN'],
            [ 'color_name' => 'GINGER'],
            [ 'color_name' => 'BRIGHT ORANGE'],
            [ 'color_name' => 'MANDARIN'],
            [ 'color_name' => 'ORANGE'],
            [ 'color_name' => 'SPICE'],
            [ 'color_name' => 'BURNT ORANGE'],
            [ 'color_name' => 'SATIN'],
            [ 'color_name' => 'DUSKY PINK'],
            [ 'color_name' => 'PUTTY'],
            [ 'color_name' => 'SUNKISSED PINK'],
            [ 'color_name' => 'CORAL'],
            [ 'color_name' => 'SOFT PEACH'],
            [ 'color_name' => 'PEACH'],
            [ 'color_name' => 'MANGO'],
            [ 'color_name' => 'PASTEL PINK'],
            [ 'color_name' => 'COCKTAIL PINK'],
            [ 'color_name' => 'SALMON PINK'],
            [ 'color_name' => 'ANTIQUE PINK'],
            [ 'color_name' => 'LIPSTICK RED'],
            [ 'color_name' => 'RED'],
            [ 'color_name' => 'BERRY RED'],
            [ 'color_name' => 'RUBY'],
            [ 'color_name' => 'POPPY'],
            [ 'color_name' => 'CRIMSON'],
            [ 'color_name' => 'CARDINAL RED'],
            [ 'color_name' => 'BURGUNDY'],
            [ 'color_name' => 'MAROON'],
            [ 'color_name' => 'PALE PINK'],
            [ 'color_name' => 'BABY PINK'],
            [ 'color_name' => 'ROSE PINK'],
            [ 'color_name' => 'CERISE'],
            [ 'color_name' => 'HOT PINK'],
            [ 'color_name' => 'MAGENTA'],
            [ 'color_name' => 'CARMINE'],
            [ 'color_name' => 'DUSKY ROSE'],
            [ 'color_name' => 'BLOSSOM'],
            [ 'color_name' => 'PINK CARNATION'],
            [ 'color_name' => 'FUCHSIA PINK'],
            [ 'color_name' => 'SLATE'],
            [ 'color_name' => 'AMETHYST'],
            [ 'color_name' => 'PURPLE'],
            [ 'color_name' => 'MULBERRY'],
            [ 'color_name' => 'PLUM'],
            [ 'color_name' => 'AUBERGINE'],
            [ 'color_name' => 'LAVENDER'],
            [ 'color_name' => 'ORCHID'],
            [ 'color_name' => 'LILAC'],
            [ 'color_name' => 'BLUEBELL'],
            [ 'color_name' => 'VIOLET'],
            [ 'color_name' => 'PRUSSIAN'],
            [ 'color_name' => 'BLUE PEARL'],
            [ 'color_name' => 'CORNFLOWER'],
            [ 'color_name' => 'COBALT BLUE'],
            [ 'color_name' => 'CHINA BLUE'],
            [ 'color_name' => 'MIDNIGHT BLUE'],
            [ 'color_name' => 'INDIGO BLUE'],
            [ 'color_name' => 'ROYAL BLUE'],
            [ 'color_name' => 'TRUE BLUE'],
            [ 'color_name' => 'AZURE'],
            [ 'color_name' => 'SKY BLUE'],
            [ 'color_name' => 'CYAN'],
            [ 'color_name' => 'PASTEL BLUE'],
            [ 'color_name' => 'POWDER BLUE'],
            [ 'color_name' => 'ARCTIC BLUE'],
            [ 'color_name' => 'DENIM BLUE'],
            [ 'color_name' => 'AEGEAN'],
            [ 'color_name' => 'FRENCH NAVY'],
            [ 'color_name' => 'COOL AQUA'],
            [ 'color_name' => 'DUCK EGG'],
            [ 'color_name' => 'TURQUOISE'],
            [ 'color_name' => 'MARINE'],
            [ 'color_name' => 'PETROL BLUE'],
            [ 'color_name' => 'HOLLY'],
            [ 'color_name' => 'PINE'],
            [ 'color_name' => 'EMERALD'],
            [ 'color_name' => 'GREEN'],
            [ 'color_name' => 'LUSH GREEN'],
            [ 'color_name' => 'PASTEL GREEN'],
            [ 'color_name' => 'SOFT GREEN'],
            [ 'color_name' => 'MINT GREEN'],
            [ 'color_name' => 'GRASS'],
            [ 'color_name' => 'FOREST GREEN'],
            [ 'color_name' => 'TEA GREEN'],
            [ 'color_name' => 'GREY GREEN'],
            [ 'color_name' => 'MEADOW GREEN'],
            [ 'color_name' => 'APPLE'],
            [ 'color_name' => 'LEAF GREEN'],
            [ 'color_name' => 'BRIGHT GREEN'],
            [ 'color_name' => 'LIME ZEST'],
            [ 'color_name' => 'LIME GREEN'],
            [ 'color_name' => 'PEAR GREEN'],
            [ 'color_name' => 'MARSH GREEN'],
            [ 'color_name' => 'OLIVE GREEN'],
            [ 'color_name' => 'MOSS'],
            [ 'color_name' => 'PASTEL BEIGE'],
            [ 'color_name' => 'KHAKI'],
            [ 'color_name' => 'SANDSTONE'],
            [ 'color_name' => 'CARAMEL'],
            [ 'color_name' => 'COCOA'],
            [ 'color_name' => 'UMBER'],
            [ 'color_name' => 'CINNAMON'],
            [ 'color_name' => 'RAW SIENNA'],
            [ 'color_name' => 'TAN'],
            [ 'color_name' => 'TERRACOTTA'],
            [ 'color_name' => 'BURNT UMBER'],
            [ 'color_name' => 'CHESTNUT'],
            [ 'color_name' => 'HENNA'],
            [ 'color_name' => 'WALNUT'],
            [ 'color_name' => 'BURNT SIENNA'],
            [ 'color_name' => 'SHALE'],
            [ 'color_name' => 'PRIMROSE'],
            [ 'color_name' => 'WARM GREY 1'],
            [ 'color_name' => 'WARM GREY 2'],
            [ 'color_name' => 'WARM GREY 3'],
            [ 'color_name' => 'WARM GREY 4'],
            [ 'color_name' => 'WARM GREY 5'],
            [ 'color_name' => 'COOL GREY 1'],
            [ 'color_name' => 'COOL GREY 2'],
            [ 'color_name' => 'COOL GREY 3'],
            [ 'color_name' => 'COOL GREY 4'],
            [ 'color_name' => 'COOL GREY 5'],
            [ 'color_name' => 'ICE GREY 1'],
            [ 'color_name' => 'ICE GREY 2'],
            [ 'color_name' => 'ICE GREY 3'],
            [ 'color_name' => 'ICE GREY 4'],
            [ 'color_name' => 'ICE GREY 5'],
            [ 'color_name' => 'BLACK'],
            [ 'color_name' => 'BLENDER']
        ];
        // AllColor::create($allcolor);
        foreach($allcolor as $color){
            AllColor::create($color);
        }
    }
}
